# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bdc754f225bac660364371a8834499f4f652fe8abeddfd34522c6cf178fd65a03bdc747ab4de8efa848962d9fbcd8bb9e92f9772571fc40f810d353ea9f7f985

test:
  secret_key_base: 6c40c4ca8c1aa4425e9de000da63ac8767b23eb82ef36df6d58d3cc0964b5accf7708a803f857c3d61891adbc748f44475aaa842c3f552dcd6d72798baee94ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
